import {
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  BellIcon,
  BookOpenIcon,
  BroomIcon,
  BugIcon,
  ChatCircleIcon,
  CheckIcon,
  CircleIcon,
  ClockIcon,
  CodeIcon,
  DatabaseIcon,
  EyeIcon,
  FileTextIcon,
  FlaskIcon,
  FolderIcon,
  GearIcon,
  GitBranchIcon,
  GitPullRequestIcon,
  GlobeIcon,
  HardDrivesIcon,
  type Icon,
  LayoutIcon,
  LightningIcon,
  LinkIcon,
  ListChecksIcon,
  MagnifyingGlassIcon,
  PackageIcon,
  PlayIcon,
  PlugIcon,
  PlusIcon,
  RobotIcon,
  RocketIcon,
  SparkleIcon,
  StarIcon,
  StopIcon,
  TerminalWindowIcon,
  UserIcon,
  WarningIcon,
  WrenchIcon,
  XIcon,
} from '@phosphor-icons/react'
import type { ViewIcon } from '@shared/views'

const ICONS: Record<ViewIcon, Icon> = {
  lightning: LightningIcon,
  play: PlayIcon,
  stop: StopIcon,
  terminal: TerminalWindowIcon,
  globe: GlobeIcon,
  folder: FolderIcon,
  file: FileTextIcon,
  'git-branch': GitBranchIcon,
  'git-pull-request': GitPullRequestIcon,
  bug: BugIcon,
  rocket: RocketIcon,
  sparkle: SparkleIcon,
  robot: RobotIcon,
  code: CodeIcon,
  book: BookOpenIcon,
  gear: GearIcon,
  wrench: WrenchIcon,
  refresh: ArrowsClockwiseIcon,
  search: MagnifyingGlassIcon,
  database: DatabaseIcon,
  package: PackageIcon,
  flask: FlaskIcon,
  eye: EyeIcon,
  link: LinkIcon,
  chat: ChatCircleIcon,
  checklist: ListChecksIcon,
  broom: BroomIcon,
  bell: BellIcon,
  clock: ClockIcon,
  check: CheckIcon,
  warning: WarningIcon,
  x: XIcon,
  circle: CircleIcon,
  server: HardDrivesIcon,
  plug: PlugIcon,
  user: UserIcon,
  star: StarIcon,
  plus: PlusIcon,
  'arrow-right': ArrowRightIcon,
}

export function viewIcon(icon: ViewIcon | undefined): Icon {
  return icon ? ICONS[icon] : LayoutIcon
}
