import type { ActionIcon } from '@/settings/actions'
import {
  ArrowsClockwiseIcon,
  BookOpenIcon,
  BroomIcon,
  BugIcon,
  ChatCircleIcon,
  CodeIcon,
  DatabaseIcon,
  EyeIcon,
  FileTextIcon,
  FlaskIcon,
  FolderIcon,
  GearSixIcon,
  GitBranchIcon,
  GlobeIcon,
  type Icon,
  LightningIcon,
  LinkIcon,
  ListChecksIcon,
  MagnifyingGlassIcon,
  PackageIcon,
  PlayIcon,
  RobotIcon,
  RocketIcon,
  SparkleIcon,
  TerminalWindowIcon,
  WrenchIcon,
} from '@phosphor-icons/react'

const ICONS: Record<ActionIcon, Icon> = {
  lightning: LightningIcon,
  play: PlayIcon,
  terminal: TerminalWindowIcon,
  globe: GlobeIcon,
  folder: FolderIcon,
  file: FileTextIcon,
  'git-branch': GitBranchIcon,
  bug: BugIcon,
  rocket: RocketIcon,
  sparkle: SparkleIcon,
  robot: RobotIcon,
  code: CodeIcon,
  book: BookOpenIcon,
  gear: GearSixIcon,
  wrench: WrenchIcon,
  refresh: ArrowsClockwiseIcon,
  search: MagnifyingGlassIcon,
  database: DatabaseIcon,
  package: PackageIcon,
  flask: FlaskIcon,
  eye: EyeIcon,
  link: LinkIcon,
  chat: ChatCircleIcon,
  checklist: ListChecksIcon,
  broom: BroomIcon,
}

export function actionIcon(icon: ActionIcon | undefined): Icon {
  return icon ? ICONS[icon] : LightningIcon
}
